# Generated by Django 2.2.13 on 2020-08-13 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0006_idresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idresult',
            name='object',
        ),
    ]
