# Generated by Django 2.2.13 on 2020-08-13 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flexform', '0005_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexform.Form')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexform.Object')),
            ],
        ),
    ]
