# Generated by Django 2.2.13 on 2020-08-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexform', '0009_auto_20200819_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
    ]
