# Generated by Django 2.2.13 on 2020-08-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexform', '0010_object_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
