# Generated by Django 2.2.13 on 2020-08-20 18:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flexform', '0012_formmembers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormMembers',
            new_name='FormMember',
        ),
    ]
