# Generated by Django 2.2.13 on 2020-08-20 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flexform', '0013_auto_20200820_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formmember',
            old_name='permission',
            new_name='role',
        ),
    ]
