# Generated by Django 2.2.13 on 2020-09-01 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flexform', '0014_auto_20200820_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formmember',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='flexform.Form'),
        ),
        migrations.AlterField(
            model_name='idresult',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='flexform.Form'),
        ),
        migrations.AlterField(
            model_name='object',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object', to='flexform.Form'),
        ),
        migrations.AlterField(
            model_name='result',
            name='id_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_detail', to='flexform.IdResult'),
        ),
    ]
