# Generated by Django 2.2.13 on 2021-02-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexform', '0015_auto_20200901_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'String'), (2, 'Number'), (3, 'Image')]),
        ),
    ]
