# Generated by Django 2.2.13 on 2021-02-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexform', '0022_auto_20210211_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
