# Generated by Django 2.2.13 on 2021-02-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexform', '0025_auto_20210211_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='image',
            field=models.ImageField(null=True, upload_to='profileimage'),
        ),
    ]
