# Generated by Django 2.2.13 on 2021-02-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexform', '0027_auto_20210211_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='image',
            field=models.ImageField(upload_to='uploads/images'),
        ),
    ]
