# Generated by Django 2.2.13 on 2021-02-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexform', '0028_auto_20210211_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='image',
            field=models.ImageField(upload_to='media/uploads/images'),
        ),
    ]
